const Sequelize = require('sequelize');

const sequelize = new Sequelize({
  database: 'crossword',
  dialect: 'postgres',
  operatorsAliases: false,
  define: {
    underscored: true, // use underscored column names for columns generated by sequelize (e.g. timestamps as created_at rather than createdAt)
  }
});

const User = sequelize.define('users', {
  email: {type: Sequelize.STRING, primaryKey: true},
  gamesPlayed: {type: Sequelize.INTEGER, defaultValue: 0, allowNull: false},
  bestTime: {type: Sequelize.INTEGER, allowNull: true}
});

const SavedGame = sequelize.define('saved_games', {
  puzzle: {type: Sequelize.TEXT, allowNull: false},
  usersPositions: {type: Sequelize.TEXT, allowNull: false}
});

SavedGame.belongsTo(User);
User.hasMany(SavedGame, {onDelete: 'cascade'});

module.exports = {
  sequelize,
  User,
  SavedGame
};
